name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.73.0  # Yhteensopiva versio Montereyn kanssa
        profile: minimal    # Vain olennaiset komponentit
        override: true  

    - name: Install dependencies
      run: npm install

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@1.2.0  # Yhteensopiva Tauri CLI


    - name: Build Tauri app
      run: npm run tauri build

    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v3
      with:
        name: todo_macos-app
        path: src-tauri/target/release/bundle/macos/*.app
